name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t rampeddireddi/stormledgers-frontend \
          --build-arg REACT_APP_NODE_ENV=production \
          --build-arg REACT_APP_SERVER_BASE_URL=http://54.90.124.52:4000 \
          --build-arg VITE_API_KEY=${{ secrets.VITE_API_KEY }} \
          .

      - name: Publish Image to Docker Hub
        run: docker push rampeddireddi/stormledgers-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull rampeddireddi/stormledgers-frontend:latest

      - name: Delete old container
        run: docker rm -f reactjs-app-container || true

      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container rampeddireddi/stormledgers-frontend
